services:
  - docker

script:
  - docker build -t sylvainlectra/rickroll:latest .
  - docker run -d sylvainlectra/rickroll:latest && sleep 10
  - docker inspect $(docker ps -q)
  - curl -v -s http://172.17.0.2/thisisabogusendpoint > curl.out
  - diff -u src/index.html curl.out 

after_success:
- |-
  if [[ "$TRAVIS_TAG" != "" ]]; then
    curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "'$TRAVIS_BRANCH'"}' -X POST https://registry.hub.docker.com/u/sylr/rickroll/trigger/$DOCKERHUB_TRIGGER_TOKEN/
  fi
- |-
  if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "'$TRAVIS_BRANCH'"}' -X POST https://registry.hub.docker.com/u/sylr/rickroll/trigger/$DOCKERHUB_TRIGGER_TOKEN/
  fi
